### ISSUE TITLE
Updates so new remote modules use `main` as the default branch

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKModuleTemplate#117]
We will need to make updates to:

- Associated documentation (?)
- The Cookiecutter
- The CTest script that is used

CC @jhlegarreta @dzenanz

**Comment by jhlegarreta** [comment]
Should this repository's default branch name itself stay the same?

**Comment by thewtex** [comment]
@jhlegarreta good point -- yes, we can also update this repository's default branch, too. We will need to make similar CI / doc / infra updates on the template.

**Comment by SimonRit** [comment]
Interestingly, I just renamed the branch of the [ITKCudaCommon](https://github.com/SimonRit/ITKCudaCommon/) (which we are currently extracting from RTK with @LucasGandel) because I was not aware of the push to rename the main branch of repositories. I can rollback to main easily in this case but should existing repositories be updated too in your opinion?

**Comment by thewtex** [comment]
> Interestingly, I just renamed the branch of the ITKCudaCommon (which we are currently extracting from RTK with @LucasGandel)

This is awesome! :rocket: 

@SimonRit it is not feasible to update all the repositories in the community due to infrastructure overhead, but if you are motivated, and it will work on your repository, then go for it. We do not have remote module infrastructure set up, yet, but this is a good tracking issue.

**Comment by thewtex** [comment]
thank you @jhlegarreta :pray:
