### ISSUE TITLE
Bump Python builds for itk-5.3rc4.post3

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKModuleTemplate#133]
@LucasGandel @tbirdso builds / packages have been uploaded to test the issues and changes discussed for remote module builds 5.3rc4.post3. Please give it a try!

**Comment by tbirdso** [comment]
Thanks @thewtex. Was this built against the same ITK cxx git hash as 5.3rc04.post2? (https://github.com/InsightSoftwareConsortium/ITK/commit/835dc01388d22c4b4c9a46b01dbdfe394ec23511)

**Comment by thewtex** [comment]
No, these are built against `ITK` 171fb2ba33a87041f99328a2f26612ff33aa9cc8

**Comment by thewtex** [comment]
Re: https://github.com/InsightSoftwareConsortium/ITKPythonPackage/issues/201 we should also bump the macos runner to `macos-11`.

**Comment by SimonRit** [comment]
Thanks! Giving it a try, I seem to have some download issues, see [here](https://github.com/SimonRit/RTK/actions/runs/3130262738/jobs/5080313566#step:5:25). Indeed, the names of the linux archives have changed between [v5.3rc04.post2](https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc04.post2) and [v5.3rc04.post3](https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc04.post3). Was this intentional?

**Comment by thewtex** [comment]
@SimonRit sorry, I forgot to mention that the Linux tarball names were clarified so

> for tarball in "" "-manylinux2014"; do

Needs to be updated to:

> for tarball in "-manylinux_2_28" "-manylinux2014"; do

**Comment by thewtex** [comment]
@SimonRit we are finding a few more issues -- once this PR is green: https://github.com/InsightSoftwareConsortium/ITKSplitComponents/pull/62 @tbirdso will follow up here.

**Comment by SimonRit** [comment]
Thanks. I had (eventually) guessed this SimonRit/RTK@eafbfec9683108f237e4ac1c98b7e7839a76899e + I have updated the ITK python tag SimonRit/RTK@2e629e10f15c6b6c90b8606764eaa5fff4e38b28 the  but it did not work out. One issue is InsightSoftwareConsortium/ITK#3556 (for [build-test-cxx (ubuntu-20.04)](https://github.com/SimonRit/RTK/actions/runs/3136143273/jobs/5097564160#logs), see also the [dashboard](https://my.cdash.org/build/2222201)). I don't know what's wrong for  [the Python module](https://github.com/SimonRit/RTK/actions/runs/3136143273/jobs/5097563743#logs)... See action [here](https://github.com/SimonRit/RTK/actions/runs/3136143273).

**Comment by tbirdso** [comment]
ITKSplitComponents CI is passing following updates in https://github.com/InsightSoftwareConsortium/ITKSplitComponents/pull/62 along with patches to ITKPythonPackage scripts in https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/206. Patches have been retroactively applied to ITK Python build archives at https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/tag/v5.3rc04.post3.

**Comment by dzenanz** [comment]
@tbirdso can this be closed now?

**Comment by SimonRit** [comment]
> @SimonRit please apply the changes in https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/pull/135/files and then see notes in [InsightSoftwareConsortium/ITKPythonPackage#205](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/issues/205) for the RTK build investigation.

These changes have already been applied in SimonRit/RTK#510. RTK has not changed much and used to compile with ITK 5.3rc4.post2, see e.g. https://github.com/SimonRit/RTK/actions/runs/2878570103. There is clearly an issue with InsightSoftwareConsortium/ITK#3556 since if I revert the corresponding ITK commit, the linux build succeeds (see https://github.com/SimonRit/RTK/actions/runs/3182160673/jobs/5188134114 with https://github.com/SimonRit/RTK/pull/510/commits/c568b79445823fd4af3ab396b8283ed83edfccbe). I'm honestly lost and a bit frustrated but I'll try to find time to understand the issue. It might be an RTK issue but I had pointed out in InsightSoftwareConsortium/ITK#3556 that it does not seem to be the only module with the same problem.
